import { useRef } from 'react';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import { 
  ArrowLeft, 
  Download, 
  Printer, 
  CheckCircle2,
  Building2,
  Calendar,
  Hash,
  FileText
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Bill } from '@/types/inventory';
import { Separator } from '@/components/ui/separator';

interface BillSummaryProps {
  bill: Bill;
  onBack: () => void;
}

const BillSummary = ({ bill, onBack }: BillSummaryProps) => {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const printContent = printRef.current;
    if (!printContent) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Bill ${bill.billNumber}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
            .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
            .logo { font-size: 24px; font-weight: bold; color: #10b981; }
            .bill-info { text-align: right; }
            .bill-number { font-size: 18px; font-weight: 600; }
            .bill-date { color: #6b7280; margin-top: 4px; }
            table { width: 100%; border-collapse: collapse; margin: 24px 0; }
            th { background: #1a1a2e; color: white; padding: 12px; text-align: left; font-weight: 600; }
            td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
            .total-row { background: #f9fafb; }
            .grand-total { font-size: 24px; font-weight: bold; text-align: right; margin-top: 24px; }
            .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">InvenTrack</div>
            <div class="bill-info">
              <div class="bill-number">${bill.billNumber}</div>
              <div class="bill-date">${format(bill.date, 'MMMM dd, yyyy • hh:mm a')}</div>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Product</th>
                <th>Supplier</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              ${bill.items.map((item, index) => `
                <tr>
                  <td>${index + 1}</td>
                  <td>${item.productName}</td>
                  <td>${item.supplierName}</td>
                  <td>${item.quantity}</td>
                  <td>${item.unitName}</td>
                  <td>$${item.price.toFixed(2)}</td>
                  <td>$${item.total.toFixed(2)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="grand-total">Grand Total: $${bill.grandTotal.toFixed(2)}</div>
          <div class="footer">
            Generated by InvenTrack • ${format(new Date(), 'yyyy')}
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;

    // Header
    doc.setFontSize(24);
    doc.setTextColor(16, 185, 129); // Primary green
    doc.text('InvenTrack', 20, yPos);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('Inventory Management System', 20, yPos + 8);

    // Bill info (right aligned)
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 60);
    doc.text(bill.billNumber, pageWidth - 20, yPos, { align: 'right' });
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(format(bill.date, 'MMMM dd, yyyy • hh:mm a'), pageWidth - 20, yPos + 8, { align: 'right' });

    yPos += 30;

    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(20, yPos, pageWidth - 20, yPos);
    yPos += 15;

    // Table header
    const colWidths = [12, 40, 35, 18, 25, 25, 25];
    const headers = ['#', 'Product', 'Supplier', 'Qty', 'Unit', 'Price', 'Total'];
    
    doc.setFillColor(26, 26, 46);
    doc.rect(20, yPos - 6, pageWidth - 40, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    
    let xPos = 22;
    headers.forEach((header, i) => {
      doc.text(header, xPos, yPos);
      xPos += colWidths[i];
    });

    yPos += 10;

    // Table rows
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 50, 50);
    
    bill.items.forEach((item, index) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      xPos = 22;
      const rowData = [
        `${index + 1}`,
        item.productName.substring(0, 18),
        item.supplierName.substring(0, 16),
        `${item.quantity}`,
        item.unitName,
        `$${item.price.toFixed(2)}`,
        `$${item.total.toFixed(2)}`
      ];

      rowData.forEach((text, i) => {
        doc.text(text, xPos, yPos);
        xPos += colWidths[i];
      });

      // Row separator
      doc.setDrawColor(230, 230, 230);
      doc.line(20, yPos + 3, pageWidth - 20, yPos + 3);
      yPos += 10;
    });

    yPos += 10;

    // Grand Total
    doc.setFillColor(245, 245, 250);
    doc.rect(pageWidth - 80, yPos - 5, 60, 20, 'F');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Grand Total', pageWidth - 75, yPos + 2);
    doc.setFontSize(16);
    doc.setTextColor(30, 30, 60);
    doc.setFont('helvetica', 'bold');
    doc.text(`$${bill.grandTotal.toFixed(2)}`, pageWidth - 75, yPos + 12);

    yPos += 40;

    // Footer
    doc.setDrawColor(200, 200, 200);
    doc.line(20, yPos, pageWidth - 20, yPos);
    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text('Thank you for your business!', pageWidth / 2, yPos, { align: 'center' });
    doc.text(`Generated by InvenTrack • ${format(new Date(), 'yyyy')}`, pageWidth / 2, yPos + 6, { align: 'center' });

    // Save the PDF
    doc.save(`${bill.billNumber}.pdf`);
  };

  const handleDownloadHTML = () => {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Bill ${bill.billNumber}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
            .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
            .logo { font-size: 24px; font-weight: bold; color: #10b981; }
            .bill-info { text-align: right; }
            .bill-number { font-size: 18px; font-weight: 600; }
            .bill-date { color: #6b7280; margin-top: 4px; }
            table { width: 100%; border-collapse: collapse; margin: 24px 0; }
            th { background: #1a1a2e; color: white; padding: 12px; text-align: left; font-weight: 600; }
            td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
            .grand-total { font-size: 24px; font-weight: bold; text-align: right; margin-top: 24px; }
            .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">InvenTrack</div>
            <div class="bill-info">
              <div class="bill-number">${bill.billNumber}</div>
              <div class="bill-date">${format(bill.date, 'MMMM dd, yyyy • hh:mm a')}</div>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Product</th>
                <th>Supplier</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              ${bill.items.map((item, index) => `
                <tr>
                  <td>${index + 1}</td>
                  <td>${item.productName}</td>
                  <td>${item.supplierName}</td>
                  <td>${item.quantity}</td>
                  <td>${item.unitName}</td>
                  <td>$${item.price.toFixed(2)}</td>
                  <td>$${item.total.toFixed(2)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="grand-total">Grand Total: $${bill.grandTotal.toFixed(2)}</div>
          <div class="footer">
            Generated by InvenTrack • ${format(new Date(), 'yyyy')}
          </div>
        </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${bill.billNumber}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-scale-in">
      {/* Header Actions */}
      <div className="flex items-center justify-between no-print">
        <Button variant="ghost" onClick={onBack} className="gap-2">
          <ArrowLeft className="w-4 h-4" />
          Back to Add Inventory
        </Button>
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={handlePrint} className="gap-2">
            <Printer className="w-4 h-4" />
            Print
          </Button>
          <Button variant="default" onClick={handleDownloadPDF} className="gap-2">
            <Download className="w-4 h-4" />
            Download PDF
          </Button>
          <Button variant="outline" onClick={handleDownloadHTML} className="gap-2">
            <FileText className="w-4 h-4" />
            HTML
          </Button>
        </div>
      </div>

      {/* Success Banner */}
      <div className="bg-success/10 border border-success/20 rounded-lg p-4 flex items-center gap-3">
        <CheckCircle2 className="w-6 h-6 text-success" />
        <div>
          <p className="font-medium text-foreground">Bill saved successfully!</p>
          <p className="text-sm text-muted-foreground">
            All items have been added to your inventory stock.
          </p>
        </div>
      </div>

      {/* Bill Summary Card */}
      <Card className="shadow-elevated" ref={printRef}>
        <CardContent className="p-8">
          {/* Bill Header */}
          <div className="flex items-start justify-between mb-8">
            <div>
              <h2 className="text-2xl font-bold text-primary">InvenTrack</h2>
              <p className="text-muted-foreground">Inventory Management System</p>
            </div>
            <div className="text-right">
              <div className="flex items-center gap-2 justify-end text-lg font-bold">
                <Hash className="w-5 h-5 text-muted-foreground" />
                {bill.billNumber}
              </div>
              <div className="flex items-center gap-2 justify-end text-sm text-muted-foreground mt-1">
                <Calendar className="w-4 h-4" />
                {format(bill.date, 'MMMM dd, yyyy • hh:mm a')}
              </div>
            </div>
          </div>

          <Separator className="my-6" />

          {/* Items Table */}
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-table-header text-table-header-foreground rounded-t-lg overflow-hidden">
                  <th className="px-4 py-3 text-left font-semibold text-sm rounded-tl-lg">#</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Product</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Supplier</th>
                  <th className="px-4 py-3 text-center font-semibold text-sm">Qty</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Unit</th>
                  <th className="px-4 py-3 text-right font-semibold text-sm">Price</th>
                  <th className="px-4 py-3 text-right font-semibold text-sm rounded-tr-lg">Total</th>
                </tr>
              </thead>
              <tbody>
                {bill.items.map((item, index) => (
                  <tr key={item.id} className="border-b border-table-border">
                    <td className="px-4 py-4 text-muted-foreground">{index + 1}</td>
                    <td className="px-4 py-4 font-medium">{item.productName}</td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-2">
                        <Building2 className="w-4 h-4 text-muted-foreground" />
                        {item.supplierName}
                      </div>
                    </td>
                    <td className="px-4 py-4 text-center font-medium">{item.quantity}</td>
                    <td className="px-4 py-4 text-muted-foreground">{item.unitName}</td>
                    <td className="px-4 py-4 text-right">${item.price.toFixed(2)}</td>
                    <td className="px-4 py-4 text-right font-semibold">${item.total.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <Separator className="my-6" />

          {/* Grand Total */}
          <div className="flex justify-end">
            <div className="bg-muted/50 rounded-lg px-8 py-4 text-right">
              <p className="text-sm text-muted-foreground mb-1">Grand Total</p>
              <p className="text-4xl font-bold text-foreground">
                ${bill.grandTotal.toFixed(2)}
              </p>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-12 pt-6 border-t border-border text-center text-sm text-muted-foreground">
            <p>Thank you for your business!</p>
            <p className="mt-1">Generated by InvenTrack • {format(new Date(), 'yyyy')}</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default BillSummary;
